# Generated by Django 4.2.1 on 2023-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Home & Garden', 'Home & Garden'), ('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Electronics', 'Electronics'), ('Shoes', 'Shoes'), ('Jewelries', 'Jewelries')], default='Home & Garden', max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='photos/product_image/')),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
    ]
